[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/product/:id"
  to = "/product.html?id=:id"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/post.html?slug=:slug"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200
