[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/product/:id"
  to = "/product.html?id=:id"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/post-page?slug=:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/product-feed.csv"
  to = "/.netlify/functions/product-feed"
  status = 200
